### ISSUE TITLE
using the entire area of the form when loading an stl

### ISSUE THREAD

**Issue by alexgman** [batu92k/STL-Viewer#11]
Currently, when an STL file is imported, it is displayed on the form but it is relatively small in size. I was wondering if it would be possible to implement a feature where the STL file would be displayed in a way that it takes up the entire space of the form? When this maiden is loaded, she should take up all the space that she can:

![image](https://user-images.githubusercontent.com/4227695/208585984-1a3ef4fc-2e51-4301-b9cc-ea0507a28f7b.png)

**Comment by batu92k** [comment]
Hi, I believe it's possible to do that by using the bounding box. The bounding box can be projected to XY surface depending on the initial orientation and then the size of the bounding box can be compared to the size of the window in order to determine the scale factor. To make this cleaner, it's better to finish this task first:

- https://github.com/batu92k/STL-Viewer/issues/9

Once we have the StlData class, it's easier to keep this information there and use it before drawing the object.
I will take a look at what I can do and update this thread once there is a candidate and possibly ask for your help with testing. :)

**Comment by alexgman** [comment]
thanks so much !

**Comment by batu92k** [comment]
Hi @alexgman, could you test the feature and write feedback, please? :)
It's in the branch:
 * 11-using-the-entire-area-of-the-form-when-loading-an-stl

**Comment by alexgman** [comment]
Testing today!

**Comment by alexgman** [comment]
works really nicely! thank you !

**Comment by batu92k** [comment]
Thanks for the feedback. FYI, I am now planning to implement an extended fit feature just like in the CAD programs. The issue is here:
 - https://github.com/batu92k/STL-Viewer/issues/14

Stay tuned. :)
