### ISSUE TITLE
Rotation and scale

### ISSUE THREAD

**Issue by GBEY0402** [batu92k/STL-Viewer#2]
Good project, but I'm having trouble to clear the rotation feature and make the object fit in the monitor. Planning to make it static andshow multiple stl files at once in a list view using configuration to read directly from an added folder on startup. Where can i set the proper rotation and just display it?

**Comment by batu92k** [comment]
For the orientation you can try to modify  **`Gl.glRotatef(angle, x, y, z)`** function. This function basically defines the angle of rotation according to given vector (x ,y ,z). In order to fit the object to GL monitor with a good scale; you needto find the boundary box of the object and you need to scale he object according to the ratio of your viewport and your object's boundary box. One detail with the boundary box; if you will change the orientation of your object you also need to change your boundary box according to the orientation.

**Comment by batu92k** [comment]
I also put a new sample model and a WCS reference, so you can find a good orientation by yourself by modifying **`Gl.glRotatef(angle, x, y, z)`** function.
