### ISSUE TITLE
Crash about ASCII formatted STL files

### ISSUE THREAD

**Issue by TanhuanHUST** [batu92k/STL-Viewer#5]
If I want to import an ASCII formatted STL file,It will carsh at STLreader.cs line:88  : minRefArray[0] = meshArray.Min(j => j.vert1.x);

Binary  formatted STL files works well~

**Comment by batu92k** [comment]
I just noticed that ASCII formatted *.stl files that are exported from different programs (Blender, NX etc.), have some format differences for whitespace characters. So the ASCII reading method needs to be fixed. I will take care of it. Thanks for the feedback!

**Comment by TanhuanHUST** [comment]
My stl file is generated by SolidWorks.By the way ,I found out that Left-Hand-Rule is used ，using GL.DepthRange(1.0f, 0.0f) can fix the problem. Attached is my binSTL and ASCII stl file. 


![{BE79E1D9-AAD9-49A4-B731-E26351DDB16E}_20200403094031](https://user-images.githubusercontent.com/40975604/78315901-e111c500-7590-11ea-85c8-423848fc102e.jpg)

**Comment by TanhuanHUST** [comment]
My stl file is generated by SolidWorks.By the way ,I found out that Left-Hand-Rule is used ，using GL.DepthRange(1.0f, 0.0f) can fix the problem.
![{BE79E1D9-AAD9-49A4-B731-E26351DDB16E}_20200403094031](https://user-images.githubusercontent.com/40975604/78316188-a197a880-7591-11ea-92b9-58db6436a5cb.jpg)

**Comment by TanhuanHUST** [comment]
Attached is my binSTL and ASCII stl file.

**Comment by batu92k** [comment]
That's a good point. It could also be caused by the Orthographic projection configuration while defining Z-Far and Z-Near. I will also check this one.

**Comment by batu92k** [comment]
I fixed the read method for ASCII formatted files, also about the dept range it turned out I could solve it by reverting Z Far and Z Near during the **Orthographic projection configuration** or set **GL.DepthRange(1.0f, 0.0f)** as you said. So I prefer to make it by changing the configuration in order to avoid an extra function call. I pushed those commits that fix the problem to **Develop** branch. There is just one problem with the Mouse Orbit feature which I needed to revert the X and Y axis of my orbit vector due to the change of the Ortho configuration. In this case, I need to update the Mouse Orbit project after I make sure these fixes are ok.

So, can you check the **Develop** branch about if the fixed version also works for you? I added a small routine in **Develop** branch that draws a coordinate system on the screen to make debug process easier.

If you write your feedback here after testing the **Develop** branch I would be appreciated.

Cheers
Batu

**Comment by TanhuanHUST** [comment]
Yes! both issues are verified and resolved~
